// Auto-generated from white-label config
// Do not edit this file manually - it will be overwritten

const light = {
  "text": "#1F2937",
  "textSecondary": "#6B7280",
  "background": "#FFFFFF",
  "backgroundSecondary": "#F9FAFB",
  "tint": "#DC143C",
  "primary": "#DC143C",
  "secondary": "#1E3A8A",
  "accent": "#F59E0B",
  "success": "#10B981",
  "warning": "#F59E0B",
  "error": "#EF4444",
  "tabIconDefault": "#9CA3AF",
  "tabIconSelected": "#DC143C",
  "card": "#FFFFFF",
  "border": "#E5E7EB",
  "shadow": "#00000015"
};
const dark = {
  "text": "#F9FAFB",
  "textSecondary": "#9CA3AF",
  "background": "#111827",
  "backgroundSecondary": "#1F2937",
  "tint": "#FF4757",
  "primary": "#FF4757",
  "secondary": "#3B82F6",
  "accent": "#FBBF24",
  "success": "#34D399",
  "warning": "#FBBF24",
  "error": "#F87171",
  "tabIconDefault": "#6B7280",
  "tabIconSelected": "#FF4757",
  "card": "#1F2937",
  "border": "#374151",
  "shadow": "#00000040"
};

export default {
  light,
  dark,
};
