// Runtime white-label configuration loader
// This file provides runtime access to white-label config
// The config is imported from the generated whitelabels/config.json file

// Import the active white-label config (generated by the switch script)
// This file is generated when you run the switch script
import whitelabelConfig from '../config.json';

export interface WhiteLabelConfig {
  name: string;
  slug: string;
  version: string;
  scheme: string;
  owner: string;
  easProjectId: string;
  routerOrigin: string;
  instantDbAppId: string;
  bundleIdentifier: {
    ios: string;
    android: string;
  };
  colors: {
    light: Record<string, string>;
    dark: Record<string, string>;
  };
  branding: {
    welcomeTitle: string;
    splashBackgroundColor: string;
  };
  icons?: {
    icon: string;
    splash: string;
    adaptiveIcon: string;
    favicon: string;
  };
}

/**
 * Get the current white-label configuration at runtime
 * This reads from the generated whitelabels/config.json file
 */
export function getWhiteLabelConfig(): WhiteLabelConfig {
  return whitelabelConfig as WhiteLabelConfig;
}

