// Auto-generated from white-label config
// Do not edit this file manually - it will be overwritten

import { init, i, id } from '@instantdb/react-native';

// Get your APP_ID from https://instantdb.com/dash
const APP_ID = 'f69eae61-f5b0-4a15-b7ba-dffea0fa17fa';

// Define the schema for InstantDB
const schema = i.schema({
  entities: {
    workouts: i.entity({
      title: i.string(),
      culturalName: i.string(),
      description: i.string(),
      duration: i.number(),
      difficulty: i.string(),
      equipment: i.json(), // Array of strings
      category: i.string(),
      caloriesBurn: i.number(),
      imageUrl: i.string(),
      createdAt: i.number(),
    }),
    exercises: i.entity({
      workoutId: i.string(),
      name: i.string(),
      reps: i.string().optional(),
      duration: i.number().optional(),
      instructions: i.json(), // Array of strings
      videoUrl: i.string().optional(),
      imageUrl: i.string().optional(),
      order: i.number(),
    }),
    nutritionTips: i.entity({
      title: i.string(),
      category: i.string(), // 'dal-bhat' | 'momo' | 'traditional' | 'modern'
      description: i.string(),
      imageUrl: i.string(),
      tips: i.json(), // Array of strings
      calories: i.number().optional(),
      protein: i.number().optional(),
      carbs: i.number().optional(),
      fat: i.number().optional(),
      createdAt: i.number(),
    }),
    // Note: $users is automatically created by InstantDB for auth
    // It contains basic info: email (main identifier), id
    // We need to reference it in the schema to use it in links
    $users: i.entity({
      email: i.string(),
    }),
    // Custom users table - contains all user information and stats
    // Linked to $users via userId (which is the $users.id)
    users: i.entity({
      userId: i.string(), // Reference to $users.id
      email: i.string(), // Duplicated from $users for easier queries
      name: i.string(),
      avatar: i.string().optional(),
      // Stats - simple numbers
      workoutStreak: i.number(),
      totalWorkouts: i.number(),
      points: i.number(),
      // Additional data
      customMetrics: i.json(), // { energyLevel, sleepQuality, lastWorkoutDate, weight }
      goals: i.json(), // Array of UserGoal
      preferences: i.json().optional(), // AchievementPreferences
      createdAt: i.number(),
      updatedAt: i.number(),
    }),
    authCodes: i.entity({
      email: i.string(),
      code: i.string(),
      expiresAt: i.number(),
      used: i.boolean(),
      createdAt: i.number(),
    }),
    workoutLogs: i.entity({
      userId: i.string(),
      workoutId: i.string(),
      date: i.string(), // ISO date string
      duration: i.number(),
      caloriesBurned: i.number(),
      energyBefore: i.number(),
      energyAfter: i.number(),
      notes: i.string().optional(),
      createdAt: i.number(),
    }),
    achievements: i.entity({
      userId: i.string(),
      achievementId: i.string(), // e.g., 'first_workout', 'week_warrior'
      title: i.string(),
      description: i.string(),
      icon: i.string(),
      unlockedDate: i.string(), // ISO date string
      createdAt: i.number(),
    }),
    socialPosts: i.entity({
      userId: i.string(),
      userName: i.string(),
      userAvatar: i.string().optional(),
      type: i.string(), // 'achievement' | 'workout' | 'milestone' | 'challenge'
      content: i.string(),
      likes: i.number(),
      likedBy: i.json().optional(), // Array of user IDs who liked this post
      comments: i.number(),
      data: i.json().optional(), // Additional post data
      createdAt: i.number(),
    }),
    comments: i.entity({
      postId: i.string(), // Reference to socialPosts.id
      userId: i.string(),
      userName: i.string(),
      userAvatar: i.string().optional(),
      content: i.string(),
      createdAt: i.number(),
    }),
    // User workout instances - tracks individual user progress through a workout
    // Multiple instances allowed per user per workout (one per day/session)
    userWorkouts: i.entity({
      userId: i.string(), // Reference to users.id
      workoutId: i.string(), // Reference to workouts.id
      status: i.string(), // 'not_started' | 'in_progress' | 'completed'
      completedExercises: i.json(), // Array of exercise IDs that are completed
      workoutDate: i.string(), // ISO date string (YYYY-MM-DD) to identify daily sessions
      startedAt: i.number().optional(), // Timestamp when workout was started
      completedAt: i.number().optional(), // Timestamp when workout was completed
      createdAt: i.number(),
      updatedAt: i.number(),
    }),
    // Challenges - community challenges that users can participate in
    challenges: i.entity({
      title: i.string(),
      culturalName: i.string(),
      description: i.string(),
      type: i.string(), // 'weekly' | 'monthly'
      goal: i.number(), // Target number (e.g., 29 workouts or 7 days streak)
      endDate: i.string(), // ISO date string (YYYY-MM-DD)
      reward: i.string(), // Reward description (e.g., 'Gold Badge & 500 Points')
      isActive: i.boolean(), // Whether the challenge is currently active
      metricType: i.string(), // 'streak' | 'workout_count' | 'workout_count_weekly' | 'workout_count_monthly'
      category: i.string().optional(), // Optional: WorkoutCategory for category-specific challenges
      createdAt: i.string(),
    }),
    // User challenge progress - tracks individual user progress in challenges
    userChallengeProgress: i.entity({
      userId: i.string(), // Reference to users.id
      challengeId: i.string(), // Reference to challenges.id
      progress: i.number(), // Current progress (e.g., 12 out of 29)
      completed: i.boolean(), // Whether the challenge is completed
      completedAt: i.number().optional(), // Timestamp when challenge was completed
      createdAt: i.number(),
      updatedAt: i.number(),
    }),
  },
  links: {
    workoutExercises: {
      forward: {
        on: 'workouts',
        has: 'many',
        label: 'exercises',
      },
      reverse: {
        on: 'exercises',
        has: 'one',
        label: 'workout',
      },
    },
    // Note: $users is read-only, so we can't create links FROM it
    // We store the reference in users.userId field pointing to $users.id
    // For querying, we query users table and use the userId field
    // Link users to workoutLogs
    userWorkoutLogs: {
      forward: {
        on: 'users',
        has: 'many',
        label: 'workoutLogs',
      },
      reverse: {
        on: 'workoutLogs',
        has: 'one',
        label: 'user',
      },
    },
    // Link users to achievements
    userAchievements: {
      forward: {
        on: 'users',
        has: 'many',
        label: 'achievements',
      },
      reverse: {
        on: 'achievements',
        has: 'one',
        label: 'user',
      },
    },
    // Link users to socialPosts
    userSocialPosts: {
      forward: {
        on: 'users',
        has: 'many',
        label: 'socialPosts',
      },
      reverse: {
        on: 'socialPosts',
        has: 'one',
        label: 'user',
      },
    },
    // Link socialPosts to comments
    postComments: {
      forward: {
        on: 'socialPosts',
        has: 'many',
        label: 'comments',
      },
      reverse: {
        on: 'comments',
        has: 'one',
        label: 'post',
      },
    },
    // Link users to comments
    userComments: {
      forward: {
        on: 'users',
        has: 'many',
        label: 'comments',
      },
      reverse: {
        on: 'comments',
        has: 'one',
        label: 'user',
      },
    },
    // Link users to userWorkouts
    userUserWorkouts: {
      forward: {
        on: 'users',
        has: 'many',
        label: 'userWorkouts',
      },
      reverse: {
        on: 'userWorkouts',
        has: 'one',
        label: 'user',
      },
    },
    // Link users to userChallengeProgress
    userChallengeProgress: {
      forward: {
        on: 'users',
        has: 'many',
        label: 'challengeProgress',
      },
      reverse: {
        on: 'userChallengeProgress',
        has: 'one',
        label: 'user',
      },
    },
    // Link challenges to userChallengeProgress
    challengeProgress: {
      forward: {
        on: 'challenges',
        has: 'many',
        label: 'userProgress',
      },
      reverse: {
        on: 'userChallengeProgress',
        has: 'one',
        label: 'challenge',
      },
    },
  },
});

// Initialize InstantDB
export const db = init({ 
  appId: APP_ID, 
  schema,
});

export { id };

export type Schema = typeof schema;
